from abc import ABC, abstractmethod
from typing import Any

class Lifecycle(ABC):
    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def start(self) -> None: ...
    @abstractmethod
    async def ready(self) -> None: ...
    @abstractmethod
    async def shutdown(self) -> None: ...

class Integration(ABC):
    @abstractmethod
    async def initialize(self, configuration: dict[str, Any]) -> None: ...
    @abstractmethod
    async def shutdown(self) -> None: ...
