from __future__ import annotations
import argparse
import json
from pathlib import Path
from framework.plugins.loader import PluginLoader

def scaffold(name: str, destination: Path) -> Path:
    root = destination / name; package = root / name
    package.mkdir(parents=True, exist_ok=False)
    (root / "tests").mkdir()
    (package / "__init__.py").write_text('from framework.plugins.base import PluginManifest\n\nPLUGIN_MANIFEST = PluginManifest(plugin_id="%s", name="%s", version="1.0.0", author="Developer", description="Generated extension", permissions=set())\n\nasync def initialize(context): pass\nasync def shutdown(): pass\n' % (name, name.replace("_", " ").title()))
    (root / "README.md").write_text(f"# {name}\n\nGenerated by the Framework extension scaffold. Registration is explicit.\n")
    (root / "pyproject.toml").write_text(f"[project]\nname = \"framework-{name}\"\nversion = \"1.0.0\"\nrequires-python = \">=3.11\"\ndependencies = []\n")
    return root

def main(argv=None):
    parser = argparse.ArgumentParser(prog="framework")
    sub = parser.add_subparsers(dest="command", required=True)
    plugin = sub.add_parser("plugin"); plugin_sub = plugin.add_subparsers(dest="action", required=True)
    init = plugin_sub.add_parser("init"); init.add_argument("name"); init.add_argument("--directory", default=".")
    validate = plugin_sub.add_parser("validate"); validate.add_argument("module")
    list_cmd = plugin_sub.add_parser("list")
    args = parser.parse_args(argv)
    if args.command == "plugin" and args.action == "init": print(scaffold(args.name, Path(args.directory))); return 0
    loader = PluginLoader()
    if args.action == "validate":
        module, manifest = loader.discover(args.module); loader._validate_manifest(manifest, {}); print(json.dumps({"valid": True, "plugin_id": manifest.plugin_id, "version": manifest.version})); return 0
    if args.action == "list": print(json.dumps(loader.discover_entrypoints(), indent=2)); return 0
    return 0

if __name__ == "__main__": raise SystemExit(main())
